version: "3"

services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    container_name: "postgres-container"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "soccerstats"
      POSTGRES_DB: "soccerstats"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: "redis-container"
