version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: soccerstats
      POSTGRES_DB: soccerstats
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis_container
    restart: always
    volumes:
      - redis:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    container_name: mailhog_container
    restart: always
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - mailhog:/maildir

volumes:
  database:
    name: postgres_volume_soccerstats
    driver: local

  redis:
    name: redis_volume_soccerstats
    driver: local

  mailhog:
    name: mailhog_volume_soccerstats
    driver: local
