version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: soccerstats
      POSTGRES_PASSWORD: soccerstats
      POSTGRES_DATABASE: postgres
