version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: soccerstats
      POSTGRES_DB: soccerstats
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-container
    restart: always
    volumes:
      - redis:/data

volumes:
  database:
    name: postgres_volume_soccerstats
    driver: local
  redis:
    name: redis_volume_soccerstats
    driver: local
